Zueva_Natalia_ORM/MVCTESTORMPROJECT/Controllers/LibraryController.cs
using MVCTESTORMPROJECT.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCTESTORMPROJECT.Controllers
{
    public class LibraryController : Controller
    {
        MyContext context = new MyContext("MyConName");
        List<Book> _BookModel;
        public ActionResult Index()
        {
            _BookModel = context.Books.GetList().ToList();
            return View("Index", _BookModel);
        }

        [HttpGet]
        public ActionResult AddBook()
        {
            return View(new Book());
        }

        [HttpPost]
        public ActionResult AddBook(Book model)
        {
            try
            {
                context.Books.CreateNew(model);
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                ModelState.AddModelError(string.Empty, e.Message);

                Exception inner = e.InnerException;

                while (inner != null)
                {
                    ModelState.AddModelError(string.Empty, inner.Message);
                    inner = inner.InnerException;
                }
            }
            return View();
        }


        [HttpGet]
        public ActionResult Delete(int id)
        {
            context.Books.DeleteById(id);
            return Index();
        }


        public ActionResult EditBook(int id)
        {
            Book book = context.Books.GetById(id);
            return View("EditBook", book);
        }


        [HttpPost]
        public ActionResult EditBook(Book book)
        {
            try
            {
                context.Books.Update(book);
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                ModelState.AddModelError(string.Empty, e.Message);

                Exception inner = e.InnerException;

                while (inner != null)
                {
                    ModelState.AddModelError(string.Empty, inner.Message);
                    inner = inner.InnerException;
                }
            }
            return View();
        }



    }

}

Zueva_Natalia_ORM/MVCTESTORMPROJECT/Views/Library/AddBook.cshtml
@model MVCTESTORMPROJECT.Entity.Book
@{
    ViewBag.Title = "Добавление новой книги";
}

<div class="title">
    <h2>@ViewBag.Title</h2>
</div>
<br />
@using (Html.BeginForm()) {
    <div class="row">
        <div class="span12">
            @Html.ValidationSummary(true)
        </div>
    </div>
    
    <div class="row">
        <div class="span4 control-group">
            <div>@Html.LabelFor(model => model.Name)</div>
            <div>@Html.TextBoxFor(model =>model.Name)</div>
        </div>
    </div>
        <div class="row">
        <div class="span4 control-group">
            <div>@Html.LabelFor(model => model.Author)</div>
            <div>@Html.TextBoxFor(model =>model.Author)</div>
        </div>
    </div>
    <br/><br/><br/>
    <div class="row">
        <div class="span12 control-group">
            <button class="btn btn-primary" type="submit" >Сохранить</button>
            @Html.ActionLink("Назад к списку", "Index", "Book", new {@class= "btn btn-warning"})
        </div>
    </div>
}

Zueva_Natalia_ORM/MVCTESTORMPROJECT/Views/Library/EditBook.cshtml
@model MVCTESTORMPROJECT.Entity.Book
@{
    ViewBag.Title = "Редактирование книги";
}
@{var _idBank = Model.Id.ToString();}
<div class="title">
    <h2>@ViewBag.Title</h2>
</div>
<br />
@using (Html.BeginForm()) {
    <div class="row">
        <div class="span12">
            @Html.ValidationSummary(true)
        </div>
    </div>
     @Html.HiddenFor(model => model.Id)
    <div class="row">
        <div class="span4 control-group">
            <div>@Html.LabelFor(model => model.Name)</div>
            <div>@Html.TextBoxFor(model =>model.Name)</div>
        </div>
    </div>
    <div class="row">
        <div class="span4 control-group">
            <div>@Html.LabelFor(model => model.Author)</div>
            <div>@Html.TextBoxFor(model =>model.Author)</div>
        </div>
    </div>
    <br/><br/><br/>
    <div class="row">
        <div class="span12 control-group">
            <button class="btn btn-primary" type="submit" >Сохранить</button>
            @Html.ActionLink("Назад к списку", "Index", "Bank", new {@class= "btn btn-warning"})
        </div>
    </div>
}

Zueva_Natalia_ORM/MVCTESTORMPROJECT/Views/Library/Index.cshtml
@model List<MVCTESTORMPROJECT.Entity.Book>
@{
    ViewBag.Title = "Список книг";
}

<h2>@ViewBag.Title</h2>
<br/>
    @Html.ActionLink("Добавить книгу", "AddBook", "Library", new {@class= "btn btn-default"})
<br/><br/>
<table >
    <thead>
        <tr>
            <th>Название книги</th>
            <th>Автор</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model != null)
        {
            foreach (var item in Model)
            {
                <tr>
                    <td>@item.Name</td>
                    <td>@item.Author</td>
                     <td>
                        <a style="padding:5px" href="@Url.Action("Delete", "Library", new { @id = @item.Id})">Удалить</a>
                        <a style="padding:5px" href="@Url.Action("EditBook", "Library", new { @id = @item.Id})">Изменить</a>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

Zueva_Natalia_ORM/MVCTESTORMPROJECT/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.7.1.min.js")" type="text/javascript"></script>
</head>
<body>
    <div class="page">
        <div id="header">
            <div id="title" style="width:100%">
                <h1 align="center">Библиотека</h1>
            </div>
            <br/>
        </div>
        <div id="main">
            @RenderBody()
        </div>
        <div id="footer">
        </div>
    </div>
</body>
</html>